from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# Each class becomes one table in MySQL when db.create_all() runs

class User(db.Model):
    # Admin accounts, seeded with email only, password set on first login
    __tablename__ = "users"

    id            = db.Column(db.Integer, primary_key=True)
    email         = db.Column(db.String(200), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=True)  # null until first login
    role          = db.Column(db.String(50),  default="admin")
    created_at    = db.Column(db.DateTime,    server_default=db.func.now())


class SyllabusEntry(db.Model):
    # syllabi collected from institutions, managed via admin console
    __tablename__ = "syllabus_entries"

    id               = db.Column(db.Integer, primary_key=True)
    course           = db.Column(db.String(1000)) 
    institution      = db.Column(db.String(1000), nullable=False) 
    discipline       = db.Column(db.String(500))  
    policy_text      = db.Column(db.Text,        nullable=False)
    contributor      = db.Column(db.String(1000))  # 
    rights           = db.Column(db.String(1000))  #
    tier_id          = db.Column(db.String(5),   nullable=False)
    compliance_id    = db.Column(db.String(5),   nullable=False)
    enforcement_id   = db.Column(db.String(5),   nullable=False)
    notes            = db.Column(db.Text)
    school_level     = db.Column(db.String(100))
    institution_type = db.Column(db.String(100))
    state_region     = db.Column(db.String(100))
    country          = db.Column(db.String(100))
    link             = db.Column(db.String(500))
    status           = db.Column(db.String(20),  default="verified")
    created_at       = db.Column(db.DateTime,    server_default=db.func.now())

    def to_dict(self):
        return {
            "id":               self.id,
            "course":           self.course,
            "institution":      self.institution,
            "discipline":       self.discipline,
            "policy_text":      self.policy_text,
            "tier_id":          self.tier_id,
            "compliance_id":    self.compliance_id,
            "enforcement_id":   self.enforcement_id,
            "notes":            self.notes,
            "school_level":     self.school_level,
            "institution_type": self.institution_type,
            "state_region":     self.state_region,
            "country":          self.country,
            "link":             self.link,
            "status":           self.status,
            "created_at":       str(self.created_at),
        }


class BuilderQuestion(db.Model):
    # questions shown on the policy builder quiz page
    __tablename__ = "builder_questions"

    id          = db.Column(db.Integer, primary_key=True)
    step_number = db.Column(db.Integer, nullable=False)
    category    = db.Column(db.String(100), nullable=False)  # e.g., "Educational Alignment"
    question    = db.Column(db.String(500), nullable=False)
    
    option_a_title = db.Column(db.String(200), nullable=False)
    option_a_desc  = db.Column(db.String(500), nullable=False)
    option_a_value = db.Column(db.String(100), nullable=False)
    
    option_b_title = db.Column(db.String(200), nullable=False)
    option_b_desc  = db.Column(db.String(500), nullable=False)
    option_b_value = db.Column(db.String(100), nullable=False)
    
    option_c_title = db.Column(db.String(200), nullable=False)
    option_c_desc  = db.Column(db.String(500), nullable=False)
    option_c_value = db.Column(db.String(100), nullable=False)


class PolicyGenerated(db.Model):
    # Policies generated by faculty via the builder
    __tablename__ = "policies"

    id            = db.Column(db.Integer, primary_key=True)
    course_name   = db.Column(db.String(200), nullable=False)
    policy_text   = db.Column(db.Text,        nullable=False)
    tier_id       = db.Column(db.String(10),  nullable=False)
    compliance_id = db.Column(db.String(10),  nullable=False)
    created_at    = db.Column(db.DateTime,    server_default=db.func.now())
